run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: tab

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - c *gin.Context

  gosec:
    config:
      G101:
        pattern: "(?i)passwd|pass|password|pwd|secret|private_key|toke"
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"

linters:
  enable-all: true
  disable:
    - golint
    - maligned
    - scopelint
    - interfacer
    - exhaustivestruct
    - wrapcheck

issues:
  exclude:
    - Module|globalLogger|zapLogger is a global variable
    - LogMode returns interface
    - Function 'LogEvent' is too long
    - calculated cyclomatic complexity for function LogEvent is
    - "`httpService` is unused"
